
ENQUEUE-MAP-IMAGE 
CREATE-IMAGE-3D 
CREATE-IMAGE-2D 
CREATE-IMAGE 
ENQUEUE-MAP-BUFFER 
CREATE-SUB-BUFFER 
CREATE-BUFFER 
CREATE-USER-EVENT 
CREATE-SAMPLER 
CREATE-COMMAND-QUEUE 
CREATE-PROGRAM-WITH-BUILTIN-KERNELS 
CREATE-PROGRAM-WITH-BINARY 
CREATE-PROGRAM-WITH-SOURCE 
CREATE-KERNEL 
CREATE-CONTEXT-FROM-TYPE 
CREATE-CONTEXT 

