CREATE-CONTEXT
CREATE-CONTEXT-FROM-TYPE
RELEASE-CONTEXT
RETAIN-CONTEXT
GET-CONTEXT-INFO

CREATE-KERNEL
CREATE-KERNELS-IN-PROGRAM
RELEASE-KERNEL
RETAIN-KERNEL
SET-KERNEL-ARG
GET-KERNEL-INFO
GET-KERNEL-WORK-GROUP-INFO
GET-KERNEL-ARG-INFO

CREATE-PROGRAM-WITH-SOURCE
CREATE-PROGRAM-WITH-BINARY
CREATE-PROGRAM-WITH-BUILTIN-KERNELS
RETAIN-PROGRAM
RELEASE-PROGRAM
GET-PROGRAM-INFO
BUILD-PROGRAM
GET-PROGRAM-BUILD-INFO

CREATE-COMMAND-QUEUE
RELEASE-COMMAND-QUEUE
RETAIN-COMMAND-QUEUE
GET-COMMAND-QUEUE-INFO

ENQUEUE-MARKER
ENQUEUE-BARRIER
ENQUEUE-TASK
ENQUEUE-UNMAP-MEM-OBJECT
ENQUEUE-ND-RANGE-KERNEL
ENQUEUE-WAIT-FOR-EVENTS
ENQUEUE-NATIVE-KERNEL
ENQUEUE-FILL-BUFFER
ENQUEUE-FILL-IMAGE
ENQUEUE-MIGRATE-MEM-OBJECTS
ENQUEUE-MARKER-WITH-WAIT-LIST
ENQUEUE-BARRIER-WITH-WAIT-LIST

CREATE-SAMPLER
RELEASE-SAMPLER
RETAIN-SAMPLER
GET-SAMPLER-INFO

RETAIN-MEM-OBJECT
RELEASE-MEM-OBJECT
GET-MEM-OBJECT-INFO
SET-MEM-OBJECT-DESTRUCTOR-CALLBACK

RELEASE-EVENT
RETAIN-EVENT
WAIT-FOR-EVENTS
GET-EVENT-INFO
GET-EVENT-PROFILING-INFO
CREATE-USER-EVENT
SET-USER-EVENT-STATUS
SET-EVENT-CALLBACK

GET-PLATFORM-IDS
GET-PLATFORM-INFO
GET-DEVICE-IDS
GET-DEVICE-INFO
FLUSH
FINISH
UNLOAD-COMPILER

CREATE-BUFFER
CREATE-SUB-BUFFER
ENQUEUE-READ-BUFFER
ENQUEUE-WRITE-BUFFER
ENQUEUE-COPY-BUFFER
ENQUEUE-MAP-BUFFER
ENQUEUE-READ-BUFFER-RECT
ENQUEUE-WRITE-BUFFER-RECT
ENQUEUE-COPY-BUFFER-RECT

GET-IMAGE-INFO
CREATE-IMAGE
CREATE-IMAGE-2D
CREATE-IMAGE-3D
GET-SUPPORTED-IMAGE-FORMATS
ENQUEUE-WRITE-IMAGE
ENQUEUE-COPY-IMAGE-TO-BUFFER
ENQUEUE-MAP-IMAGE
ENQUEUE-READ-IMAGE
ENQUEUE-COPY-BUFFER-TO-IMAGE
ENQUEUE-COPY-IMAGE
