(in-package :eazy-opencl.host)


;;; info-getter definitions (alphabetical)

;; "returns specified info about a platform-id
;;  param = :profile, :version, :name, :vendor, :extensions"
(define-info-getter get-command-queue-info (command-queue param) (%cl:command-queue-info)
  (:queue-context         %cl:context)
  (:queue-device          %cl:device-id)
  (:queue-reference-count %cl:uint)
  (:queue-properties      %cl:command-queue-properties)
  (:queue-size            %cl:uint))

(define-info-getter get-context-info (context param) (%cl:context-info)
 (:context-reference-count %cl:uint)
 (:context-devices         %cl:device-id :array t)
 (:context-properties      %cl:context-properties :array t :plist t)
 (:context-num-devices     %cl:uint))
;; fixme : support plist stuff: alternating enum/value pairs terminated by a single 0

(define-info-getter get-device-info (device-id param) (%cl:device-info)
  (:device-address-bits                         %cl:uint)
  (:device-available                            %cl:bool)
  (:device-built-in-kernels                     :string)
  (:device-compiler-available                   %cl:bool)
  (:device-double-fp-config                     %cl:device-fp-config)
  (:device-endian-little                        %cl:bool)
  (:device-error-correction-support             %cl:bool)
  (:device-execution-capabilities               %cl:device-exec-capabilities)
  (:device-extensions                           :string)
  (:device-global-mem-cache-size                %cl:ulong)
  (:device-global-mem-cache-type                %cl:device-mem-cache-type)
  (:device-global-mem-cacheline-size            %cl:uint)
  (:device-global-mem-size                      %cl:ulong)
  (:device-global-variable-preferred-total-size %cl:size-t)
  (:device-host-unified-memory                  %cl:bool)
  (:device-image-base-address-alignment         %cl:uint)
  (:device-image-max-array-size                 %cl:size-t)
  (:device-image-max-buffer-size                %cl:size-t)
  (:device-image-pitch-alignment                %cl:uint)
  (:device-image-support                        %cl:bool)
  (:device-image2d-max-height                   %cl:size-t)
  (:device-image2d-max-width                    %cl:size-t)
  (:device-image3d-max-depth                    %cl:size-t)
  (:device-image3d-max-height                   %cl:size-t)
  (:device-image3d-max-width                    %cl:size-t)
  (:device-linker-available                     %cl:bool)
  (:device-local-mem-size                       %cl:ulong)
  (:device-local-mem-type                       %cl:device-local-mem-type)
  (:device-max-clock-frequency                  %cl:uint)
  (:device-max-compute-units                    %cl:uint)
  (:device-max-constant-args                    %cl:uint)
  (:device-max-constant-buffer-size             %cl:ulong)
  (:device-max-global-variable-size             %cl:size-t)
  (:device-max-mem-alloc-size                   %cl:ulong)
  (:device-max-on-device-events                 %cl:uint)
  (:device-max-on-device-queues                 %cl:uint)
  (:device-max-parameter-size                   %cl:size-t)
  (:device-max-pipe-args                        %cl:uint)
  (:device-max-read-image-args                  %cl:uint)
  (:device-max-read-write-image-args            %cl:uint)
  (:device-max-samplers                         %cl:uint)
  (:device-max-work-group-size                  %cl:size-t)
  (:device-max-work-item-dimensions             %cl:uint)
  (:device-max-work-item-sizes                  %cl:size-t :querysize :device-max-work-item-dimensions)
  (:device-max-write-image-args                 %cl:uint)
  (:device-mem-base-addr-align                  %cl:uint)
  (:device-min-data-type-align-size             %cl:uint)
  (:device-name                                 :string)
  (:device-native-vector-width-char             %cl:uint)
  (:device-native-vector-width-double           %cl:uint)
  (:device-native-vector-width-float            %cl:uint)
  (:device-native-vector-width-half             %cl:uint)
  (:device-native-vector-width-int              %cl:uint)
  (:device-native-vector-width-long             %cl:uint)
  (:device-native-vector-width-short            %cl:uint)
  (:device-opencl-c-version                     :string)
  (:device-parent-device                        %cl:device-id)
  (:device-partition-affinity-domain            %cl:device-affinity-domain)
  (:device-partition-max-sub-devices            %cl:uint)
  (:device-partition-properties                 %cl:device-partition-property :array t)
  (:device-partition-type                       %cl:device-partition-property :array t)
  (:device-pipe-max-active-reservations         %cl:uint)
  (:device-pipe-max-packet-size                 %cl:uint)
  (:device-platform                             %cl:platform-id)
  (:device-preferred-global-atomic-alignment    %cl:uint)
  (:device-preferred-interop-user-sync          %cl:uint)
  (:device-preferred-local-atomic-alignment     %cl:uint)
  (:device-preferred-platform-atomic-alignment  %cl:uint)
  (:device-preferred-vector-width-char          %cl:uint)
  (:device-preferred-vector-width-double        %cl:uint)
  (:device-preferred-vector-width-float         %cl:uint)
  (:device-preferred-vector-width-half          %cl:uint)
  (:device-preferred-vector-width-int           %cl:uint)
  (:device-preferred-vector-width-long          %cl:uint)
  (:device-preferred-vector-width-short         %cl:uint)
  (:device-printf-buffer-size                   %cl:size-t)
  (:device-profile                              :string)
  (:device-profiling-timer-resolution           %cl:size-t)
  (:device-queue-on-device-max-size             %cl:uint)
  (:device-queue-on-device-preferred-size       %cl:uint)
  (:device-queue-on-device-properties           %cl:command-queue-properties)
  (:device-queue-on-host-properties             %cl:command-queue-properties)
  (:device-queue-properties                     %cl:command-queue-properties)
  (:device-reference-count                      %cl:uint)
  (:device-single-fp-config                     %cl:device-fp-config)
  (:device-svm-capabilities                     %cl:device-svm-capabilities)
  (:device-type                                 %cl:device-type)
  (:device-vendor                               :string)
  (:device-vendor-id                            %cl:uint)
  (:device-version                              :string)
  (:driver-version                              :string))

(define-info-getter get-event-info (event param) (%cl:event-info)
  (:event-command-queue            %cl:command-queue)
  #+opencl-1.1
  (:event-context                  %cl:context)
  (:event-command-type             %cl:command-type)
  (:event-command-execution-status %cl:int)
  (:event-reference-count          %cl:uint))

(define-info-getter get-event-profiling-info (event param) (%cl:profiling-info)
  (:profiling-command-queued %cl:ulong)
  (:profiling-command-submit %cl:ulong)
  (:profiling-command-start  %cl:ulong)
  (:profiling-command-end    %cl:ulong)
  #+opencl-2.0
  (:profiling-command-complete %cl:ulong))

(define-info-getter get-image-info (image param) (%cl:image-info)
  (:image-format       (:pointer (:struct %cl:image-format)))
  (:image-element-size %cl:size-t)
  (:image-row-pitch    %cl:size-t)
  (:image-slice-pitch  %cl:size-t)
  (:image-width        %cl:size-t)
  (:image-height       %cl:size-t)
  (:image-depth        %cl:size-t)
  (:image-num-samples %cl:uint)
  (:image-num-mip-levels %cl:uint)
  #+opencl-1.2
  (:image-buffer %cl:mem)
  (:image-array-size %cl:size-t))

(define-info-getter get-kernel-info (kernel param) (%cl:kernel-info)
  (:kernel-attributes      :string)
  (:kernel-function-name   :string)
  (:kernel-num-args        %cl:uint)
  (:kernel-reference-count %cl:uint)
  (:kernel-context         %cl:context)
  (:kernel-program         %cl:program))

#+opencl-2.0
(define-info-getter get-kernel-exec-info (kernel param) (%cl:kernel-exec-info)
  (:kernel-exec-info-svm-ptrs (:pointer :void) :array t)
  (:kernel-exec-info-svm-fine-grain-system %cl:bool))

(define-info-getter get-kernel-work-group-info (kernel device param) (%cl:kernel-work-group-info)
  (:kernel-global-work-size                   %cl:size-t :fixedsize 3)
  (:kernel-work-group-size                    %cl:size-t)
  (:kernel-compile-work-group-size            %cl:size-t :fixedsize 3)
  (:kernel-local-mem-size          %cl:ulong)
  (:kernel-preferred-work-group-size-multiple %cl:ulong)
  (:kernel-private-mem-size                   %cl:ulong))


(define-info-getter get-mem-object-info (memobj param) (%cl:mem-info)
  (:mem-type                 %cl:mem-object-type)
  (:mem-flags                %cl:mem-flags)
  (:mem-size                 %cl:size-t)
  (:mem-host-ptr             (:pointer :void))
  (:mem-map-count            %cl:uint)
  (:mem-reference-count      %cl:uint)
  (:mem-context              %cl:context)
  ;; 1.1
  (:mem-associated-memobject %cl:mem)
  (:mem-offset               %cl:size-t)
  (:mem-uses-svm-pointer  %cl:bool))

#+opencl-2.0
(define-info-getter get-pipe-info (pipe param) (%cl:pipe-info)
  (:pipe-packet-size %cl:uint)
  (:pipe-max-packets %cl:uint))

(define-info-getter get-platform-info (platform-id param) (%cl:platform-info)
  (:platform-profile        :string)
  (:platform-version        :string)
  (:platform-name           :string)
  (:platform-vendor         :string)
  (:platform-extensions     :string)
  (:platform-icd-suffix-khr :string))

(define-info-getter get-program-build-info (program device param) (%cl:program-build-info)
  (:program-build-status  %cl:build-status)
  (:program-build-options                    :string)
  (:program-build-log                        :string)
  (:program-binary-type                      :string)
  (:program-build-global-variable-total-size :string))

(define-info-getter get-program-info (program param) (%cl:program-info)
  (:program-reference-count %cl:uint)
  (:program-context         %cl:context)
  (:program-num-devices     %cl:uint)
  (:program-devices         %cl:device-id :array t)
  (:program-source          :string)
  (:program-binary-sizes    %cl:size-t :array t)
  #+opencl-1.2
  (:program-kernel-names    :string)
  #+opencl-1.2
  (:program-num-kernels     %cl:size-t)
  (:program-binaries
   nil
   :form
   ;; fixme: test this...
   (let* ((sizes (get-program-info program :binary-sizes))
          (total-size (reduce '+ sizes)))
     (with-foreign-pointer (buffer total-size)
       (with-foreign-object (pointers '(:pointer :void) (length sizes))
         (loop for j = 0 then (+ size j)
               for size in sizes
               for i from 0
               do (setf (mem-aref pointers :pointer i) (inc-pointer buffer j)))
         (%cl/e:get-program-info program :binaries
                                 (* (foreign-type-size :pointer) (length sizes))
                                 pointers
                                 (cffi:null-pointer))
         (loop for i from 0
               for size in sizes
               collect
               (loop with array = (make-array size :element-type '(unsigned-byte 8))
                     for j below size
                     do (setf (aref array j)
                              (mem-aref (mem-aref pointers :pointer i) :uchar j))
                     finally (return array))))))))

(define-info-getter get-sampler-info (sampler param) (%cl:sampler-info)
  (:sampler-reference-count   %cl:uint)
  (:sampler-context           %cl:context)
  (:sampler-normalized-coords %cl:bool)
  (:sampler-addressing-mode   %cl:addressing-mode)
  (:sampler-filter-mode       %cl:filter-mode)
  ;; extensions, not included
  ;; (:sampler-lod-max %cl:)
  ;; (:sampler-lod-min %cl:)
  ;; (:sampler-mip-filter-mode %cl:)
  )



