
(defpackage #:eazy-opencl.bindings
  (:use :cffi)
  (:nicknames :%cl)
  (:export :UNLOAD-COMPILER
           :CHAR-16
           :CREATE-SAMPLER
           :ENQUEUE-NATIVE-KERNEL
           :GET-KERNEL-INFO
           :FLOAT
           :GET-EVENT-INFO
           :USHORT
           :GET-PLATFORM-INFO
           :ENQUEUE-WAIT-FOR-EVENTS
           :DEVICE-LOCAL-MEM-TYPE
           :USHORT-8
           :FLOAT-8
           :USHORT-4
           :USHORT-2
           :FLOAT-4
           :FLOAT-2
           :DOUBLE-8
           :DOUBLE-4
           :DOUBLE-2
           :RELEASE-PROGRAM
           :DOUBLE
           :PLATFORM-INFO
           :ULONG-8
           :ULONG-4
           :ULONG-2
           :DEVICE-EXEC-CAPABILITIES
           :KERNEL-INFO
           :DEVICE-FP-CONFIG
           :UCHAR
           :SHORT-4
           :SHORT-2
           :GET-EVENT-PROFILING-INFO
           :CHAR-8
           :CHAR-4
           :CHAR-2
           :WAIT-FOR-EVENTS
           :CREATE-IMAGE-3D
           :CREATE-IMAGE-2D
           :RETAIN-COMMAND-QUEUE
           :GET-EXTENSION-FUNCTION-ADDRESS
           :ENQUEUE-COPY-IMAGE
           :DOUBLE-16
           :RETAIN-PROGRAM
           :CREATE-PROGRAM-WITH-BINARY
           :ADDRESSING-MODE
           :GET-SUPPORTED-IMAGE-FORMATS
           :GET-PLATFORM-IDS
           :CREATE-KERNEL
           :RELEASE-MEM-OBJECT
           :RELEASE-KERNEL
           :USHORT-16
           :DEVICE-ADDRESS-INFO
           :GET-SAMPLER-INFO
           :SAMPLER-INFO
           :EVENT-INFO
           :ENQUEUE-ND-RANGE-KERNEL
           :RETAIN-EVENT
           :INT-8
           :GET-KERNEL-WORK-GROUP-INFO
           :KERNEL-WORK-GROUP-INFO
           :UCHAR-8
           :UCHAR-4
           :UCHAR-2
           :RETAIN-KERNEL
           :GET-COMMAND-QUEUE-INFO
           :CHAR
           :INT-8-T
           :INT-16
           :COMMAND-TYPE
           :UINT-8
           :UINT-4
           :UINT-2
           :ENQUEUE-UNMAP-MEM-OBJECT
           :GET-CONTEXT-INFO
           :FILTER-MODE
           :GET-MEM-OBJECT-INFO
           :ENQUEUE-COPY-BUFFER-TO-IMAGE
           :CONTEXT-INFO
           :SHORT
           :ENQUEUE-READ-IMAGE
           :HALF
           :UINT16-T
           :LONG
           :RELEASE-EVENT
           :RELEASE-COMMAND-QUEUE
           :RETAIN-CONTEXT
           :GET-DEVICE-INFO
           :DEVICE-INFO
           :INT-4
           :INT-2
           :FLOAT-16
           :MEM-OBJECT-TYPE
           :PROFILING-INFO
           :RETAIN-SAMPLER
           :ENQUEUE-MAP-IMAGE
           :BUILD-PROGRAM
           :ENQUEUE-COPY-IMAGE-TO-BUFFER
           :FINISH
           :LONG-16
           :MEM-INFO
           :ENQUEUE-WRITE-BUFFER
           :SHORT-16
           :ENQUEUE-WRITE-IMAGE
           :COMMAND-QUEUE-INFO
           :CREATE-PROGRAM-WITH-SOURCE
           :ENQUEUE-COPY-BUFFER
           :ENQUEUE-TASK
           :LONG-8
           :LONG-4
           :LONG-2
           :INT64-T
           :RELEASE-CONTEXT
           :UINT-16
           :BUILD-STATUS
           :GET-PROGRAM-INFO
           :PROGRAM-INFO
           :CREATE-BUFFER
           :MEM-FLAGS
           :CREATE-COMMAND-QUEUE
           :FLUSH
           :GET-DEVICE-IDS
           :PLATFORM-ID
           :ENQUEUE-READ-BUFFER
           :RELEASE-SAMPLER
           :SAMPLER
           :SHORT-8
           :INT16-T
           :ENQUEUE-BARRIER
           :ENQUEUE-MARKER
           :SET-KERNEL-ARG
           :SET-COMMAND-QUEUE-PROPERTY
           :COMMAND-QUEUE-PROPERTIES
           :UCHAR-16
           :UINT8-T
           :ENQUEUE-MAP-BUFFER
           :EVENT
           :MAP-FLAGS
           :BOOL
           :COMMAND-QUEUE
           :ULONG-16
           :RETAIN-MEM-OBJECT
           :CREATE-CONTEXT-FROM-TYPE
           :GET-PROGRAM-BUILD-INFO
           :PROGRAM-BUILD-INFO
           :GET-IMAGE-INFO
           :SIZE-T
           :IMAGE-INFO
           :MEM
           :CREATE-CONTEXT
           :DEVICE-ID
           :CONTEXT-PROPERTIES
           :INTPTR-T
           :CONTEXT
           :CREATE-KERNELS-IN-PROGRAM
           :KERNEL
           :PROGRAM
           :INT
           :INT32-T
           :IMAGE-FORMAT
           :IMAGE-CHANNEL-DATA-TYPE
           :IMAGE-CHANNEL-ORDER
           :CHANNEL-TYPE
           :CHANNEL-ORDER
           :DEVICE-TYPE
           :BITFIELD
           :ULONG
           :UINT64-T
           :DEVICE-MEM-CACHE-TYPE
           :UINT
           :UINT32-T
           #:error-code
           :buffer-region
           :size
           :origin

           :double-3
           :float-3
           :ulong-3
           :short-3
           :ushort-3
           :char-3
           :uchar-3
           :int-3
           :uint-3

           :gl-int
           :gl-uint
           :gl-enum

           :set-user-event-status
           :enqueue-copy-buffer-rect
           :set-mem-object-destructor-callback
           :create-sub-buffer
           :buffer-create-type
           :enqueue-read-buffer-rect
           :set-event-callback
           :enqueue-write-buffer-rect
           :create-user-event

#:create-from-gl-buffer
#:create-from-gl-texture-2d
#:create-from-gl-texture-3d
#:get-gl-context-info-khr
#:create-from-gl-renderbuffer
#:get-gl-object-info
#:get-gl-texture-info
#:enqueue-acquire-gl-objects
#:enqueue-release-gl-objects))

